### ISSUE TITLE
Thank You !

### ISSUE THREAD

**Issue by LinxGem33** [fusion809/macOS-Arc-White#4]
@fusion809 

Thank you for taking my concerns into consideration i really appreciate that.

P.s  if you need help with css and theming etc let me know id be happy to help.

**Kind regards** LinxGem33

**Comment by fusion809** [comment]
Ah on note of that help, I have one thing I'd like to ask. Where in the gtkrc (or the .rc files referenced in it like apps.rc, main.rc, *etc.*) for GTK 2 (i.e., `gtk-2.0/gtkrc`) is the menubar text colour defined? By menubar text colour I mean the colour of "File", "Edit", *etc.* in this screenshot 
![screenshot-2017-01-22-edited](https://cloud.githubusercontent.com/assets/4717341/22182944/a8410fea-e0fd-11e6-9242-9ad560b886c4.png)

**Comment by fusion809** [comment]
Nvm I fixed it myself.
